apiVersion: v1
entries:
  gitness:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-05-18T20:57:56.45137-07:00"
    description: A Helm chart for gitness
    digest: 0db2217ede8d69bf83c6a8df93b93cc96572d64ed8dddeea9f62ca24ac888f91
    name: gitness
    type: application
    urls:
    - gitness-0.1.0.tgz
    version: 0.1.0
generated: "2024-05-18T20:57:56.450967-07:00"
